# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foo": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://miklevin.github.io/mlseo/"

git_url = "https://github.com/miklevin/mlseo/tree/main/"

def custom_doc_links(name): return None
